#!/bin/bash
shopt -s nocasematch

[[ -n ${PRE_CONNECT} ]] && eval "${PRE_CONNECT}"

CHANGE_PERIOD=${CHANGE_PERIOD:-300} # 5 dakika (300 saniye) olarak varsayılan değeri ayarladık
REPEAT_PERIOD=${REPEAT_PERIOD:-7200} # 2 saat (7200 saniye) olarak varsayılan değeri ayarladık
SERVER="$1"
PREVIOUS_SERVERS=()
LAST_RESET=$(date +%s)

connect_to_server() {
  local SERVER_TO_CONNECT=$1
  current_sleep=1
  until nordvpn connect "${SERVER_TO_CONNECT}" | grep -Ei -f /opt/reg-grep
  do
    if [ ${current_sleep} -gt 32 ]
    then
      echo -e "CRITICAL\tUnable to connect; exiting"
      exit 1
    fi
    echo -e "WARNING\tUnable to connect; retrying in ${current_sleep} seconds."
    sleep ${current_sleep}
    current_sleep=$((current_sleep * 2))
  done
}

while true; do
  RECOMMENDED=$(nord_recommend)
  SERVER=$(echo "${RECOMMENDED}" | jq --raw-output .servername)

  # Önceki sunuculardan biriyle aynı sunucuya bağlanmamak için kontrol edin
  while [[ " ${PREVIOUS_SERVERS[@]} " =~ " ${SERVER} " ]]; do
    RECOMMENDED=$(nord_recommend)
    SERVER=$(echo "${RECOMMENDED}" | jq --raw-output .servername)
  done

  # Sunucuya bağlan
  connect_to_server "${SERVER}"

  # Bağlandıktan sonra CHANGE_PERIOD süresi kadar bekle
  sleep $CHANGE_PERIOD

  # Mevcut sunucuyu önceki sunucular listesine ekleyin
  PREVIOUS_SERVERS+=("${SERVER}")

  # Eğer REPEAT_PERIOD süresi dolduysa, önceki sunucular listesini sıfırla
  CURRENT_TIME=$(date +%s)
  if (( CURRENT_TIME - LAST_RESET >= REPEAT_PERIOD )); then
    PREVIOUS_SERVERS=()
    LAST_RESET=$CURRENT_TIME
  fi
done

[[ -n ${POST_CONNECT} ]] && eval "${POST_CONNECT}"

exit 0
